### ISSUE TITLE
Database add table

### ISSUE THREAD

**Issue by KevinJordil** [CPNV-ES/Joutes#24]
Hello,

Can you create a new table in database : 
Table name : **official_endpoints**
Fields : 
* name : varchar
* url : varchar

And create an **API** route /api/official_endpoints
Return table's elements in json.

Available for any questions

**Comment by phurni** [comment]
Please **DON'T DO IT**. Why?
Because official endpoints will change in time, having to synchronise the table content with real endpoints is a pain. It is a bit like code documentation, it is inside the code for reasons.

So, how to handle it? Simply annotate the "official" endpoints in the `routes/api.php` file. Side question: Are there any api endpoints that are not "official"?
Annotate is done by adding code to the route file (route plugin) so that by code you may enumerate the "offical" endpoints and returns them for your `/api/official_endpoints`.

**Comment by BenjaminDelacombaz** [comment]
I don't think we're talking about the same thing.

This table will be used to identify the official endpoints.

For example: 
* http://joutes.mycpnv.ch/api
* http://joutes.etml.ch/api
* ...

This table will not allow us to list the api application's routes because it is already done dynamically on the route: `http://joutes.mycpnv.ch/api` :+1:

**Comment by phurni** [comment]
Ok, great, no API endpoints in the DB, it was not clear from this issue description that _official_endpoints_ was those "target".

My question now is what feature this issue is related to? Do you have a Trello card which states the "As a ..., I want to list the official endpoints, So that I can ..." ?

**Comment by KevinJordil** [comment]
*backend

**Comment by JeremyGfeller** [comment]
Fixed in commit 1b53933ccd5c7f5b36a5b0bfe8409a3cfd0097a1
